AllCops:
  Exclude:
    - bin/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.5
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*_spec.rb
    - spec/support/**/*.rb
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
