AllCops:
  Exclude:
    - bin/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.5
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*_spec.rb
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Exclude:
    - lib/rails/**/*.rb
