---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
branches:
  only:
    - master
    - /.*-alpha/
    - /.*-beta/
    - /.*-stable/
before_install:
  - gem install bundler -v 1.17.3
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: rubygems
  api_key: $RUBY_GEMS_API_KEY
  on:
    tags: true
