name: Build Gem

on:
  workflow_call:

jobs:
  build:
  name: Build Gem for Ruby {{ matrix.ruby }}
  runs-on: ubuntu-latest
  steps:
    - name: Setup Branch
      uses: actions/checkout@v2

    - name: Setup Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build Gem
      run: bundle exec rake build

  strategy:
    matrix:
      ruby:
        - '2.5'
        - '2.6'
        - '2.7'
        - '3.0'
