name: Build Gem

on:
  workflow_call:
    inputs:
      ruby-version:
        default: '2.5'
        required: false
        type: string


jobs:
  build:
    name: Build Gem for Ruby ${{ inputs.ruby-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch
        uses: actions/checkout@v2

      - name: Setup Ruby ${{ inputs.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - name: Build Gem
        run: bundle exec rake build
