name: Build Gem

on:
  workflow_call:

jobs:
  build:
    name: Build Gem for Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch
        uses: actions/checkout@v4

      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Build Gem
        run: bundle exec rake build
    strategy:
      matrix:
        ruby-version:
          - '2.7'
