name: Build

on:
  pull_request:
    branches:
      - main
      - '*-alpha'
      - '*-beta'
      - '*-stable'
  push:
    branches:
      - main
      - '*-alpha'
      - '*-beta'
      - '*-stable'

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: x64
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Rake spec
        run: bundle exec rake spec
      - name: Rake build
        run: bundle exec rake build
      - name: Reporting Coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov/activeinteractor.lcov
    strategy:
      matrix:
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
