name: Build

on:
  pull_request:
    branches:
      - master
      - .*-alpha
      - .*-beta
      - .*-stable
  push:
    branches:
      - master
      - .*-alpha
      - .*-beta
      - .*-stable

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      CC_TEST_REPORTER_ID: ${{ secrets. }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: x64
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup Coverage Reporting
        run: |
          curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
          chmod +x codacy-coverage-reporter
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Rake spec
        run: bundle exec rake spec
      - name: Reporting Coverage
        run: |
          export GIT_BRANCH=${GITHUB_REF##*/}
          export GIT_COMMIT_SHA=${GITHUB_SHA}
          export CI_NAME=GITHUB
          export CI_BUILD_ID=${GITHUB_RUN_NUMBER}
          export CI_BUILD_URL=https://github.com/aaronmallen/activeinteractor/actions/runs/${GITHUB_RUN_ID}
          ./codacy-coverage-reporter report -l Java -r coverage/lcov/activeinteractor.lcov
          ./cc-test-reporter after-build
      - name: Rake build
        run: bundle exec rake build
    strategy:
      matrix:
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
