name: Build

on:
  pull_request:
    branches:
      - master
      - .*-alpha
      - .*-beta
      - .*-stable
  push:
    branches:
      - master
      - .*-alpha
      - .*-beta
      - .*-stable

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: x64
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup Coverage Reporting
        run: |
          curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
          chmod +x codacy-coverage-reporter
      - name: Rake spec
        run: bundle exec rake spec
      - name: Reporting Coverage
        run: ./codacy-coverage-reporter report -l Java --commit-uuid ${GITHUB_SHA} -r coverage/lcov/activeinteractor.lcov
      - name: Rake build
        run: bundle exec rake build
    strategy:
      matrix:
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
