name: Build

on:
  pull_request:
    branches:
      - main
      - '*-alpha'
      - '*-beta'
      - '*-dev'
      - '*-stable'
  push:
    branches:
      - main
      - '*-alpha'
      - '*-beta'
      - '*-dev'
      - '*-stable'

jobs:
  lint:
    uses: aaronmallen/activeinteractor/.github/workflows/lint.yml@main
  test:
    uses: aaronmallen/activeinteractor/.github/workflows/test.yml@main
  build:
    if: success()
    needs:
      - test
    uses: aaronmallen/activeinteractor/.github/workflows/build_gem.yml@main
