name: Lint

on:
  pull_request:
    branches:
      - main
      - '*-alpha'
      - '*-beta'
      - '*-stable'
  push:
    branches:
      - main
      - '*-alpha'
      - '*-beta'
      - '*-stable'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Setup branch
        uses: actions/checkout@v2
      - name: Set up ruby
        uses: actions/setup-ruby@v1.1.2
        with:
          ruby-version: 2.5
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
            gem install bundler
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
      - name: Rubocop run
        run: |
          bundle exec rubocop --require rubocop-performance --require code_scanning --display-cop-names
          bundle exec rubocop --require rubocop-performance --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
      - name: Upload sarif output
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rubocop.sarif
    strategy:
      fail-fast: false
